travis:
  secure:
    BINSTAR_TOKEN: kWXsfTjtOfhF0QEhvM8MvVDOLzIjeNLeC0MK81UGrNX841idzkkGKbfapc0PR+0E8gPcW0sO2r69BsZFqvBYW2h4Ux8cM8iQautlRJzWyJ/c45lqdjt5jvFsjFpkDxFhtLDETHVM1u/d0HrA2R0noz8MXLG8TyxUPCpimJ/1NpmcOPV4DBLbgocj0FyLGedGRkF2PJYIZ/GQ+hKHsFP0NzVYIbstvPIeGOISHqzeq0fVOMhFZ3HhdSiwWZ/vWEhVS7xl889nT9zcLK9BQw60+OzYI/aajQrG4CQaVRk4sxrNI0p61xwqp3IpDcRK9RtSeZCBANoUmntaiXd+5ryZ8PwjBlP434kpJ0UEFfaJS1WaACdvLtRFQhEsguJNufC1JkzSHNbAigfMQCRK3TWnFfLd8DBqZ7FJEE+ywoUBKsJlVB10qxP3RNtYihSRrMwV1fvy4VTAK6MvvN4ZQK4dZn9i+BMsCDZssv4MN3Hfamcgpm36VvPEguvCa7HBj1z5B1WnKPG7yDMacqE+3OT6nz8ZRxIXdRjxZXfSmzZiQ/8c7XQv+3RodWtPTUDaLtfujSfvaRifoUi63b2xVscyTI9HEK6M6QWx58gH2DEnXYiA3a0IOsFqfwuhYJWNNoPZmVfBe9g2f6qayJMhErnd58gA5ZjbjjZrjV6cISIEjS0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
